### ISSUE TITLE
Is it possible to show html table structure in alert message

### ISSUE THREAD

**Issue by rmdesai** [PredixDev/px-alert-message#11]
Is it possible to show html table structure in alert message, I have tried to display message in html table but it showing string instead of table like below image. 

![image](https://cloud.githubusercontent.com/assets/17174042/14203339/0c0a6366-f7c3-11e5-99b9-14c0c883b9a9.png)

Is there any way to display html component in message?

**Comment by benoitjchevalier** [comment]
The alert message doesn't support HTML at the moment. Possible enhancement.

**Comment by nonmetalhail** [comment]
@carlosfhernandez This is a feature request. Can you please prioritize this?

**Comment by rmdesai** [comment]
we need this functionality as early as possible

**Comment by vincentcn** [comment]
Any plan to support html in alert message?

**Comment by randyaskin** [comment]
I've added a light DOM slot in v1.3.0, e.g.

    <px-alert-message type="information">
      <table slot="content">
        ...
      </table>
    </px-alert-message>
