### ISSUE TITLE
Action button blank

### ISSUE THREAD

**Issue by trentgillham** [PredixDev/px-alert-message#13]
Using the dismiss or any other action will sometimes give a blank box as the action button. So if there is no auto dismiss the alert message never goes away. This happens intermittently. Sometimes to works, sometimes it doesn't. I have the most up to date version of px-alert-message.
`<px-alert-message type="custom" message-title="title" message="message" action="dismiss">`

**Comment by nonmetalhail** [comment]
Hi, we have not seen this behavior. Can you provide a fiddle replicating this issue:
https://jsfiddle.net/martinwragg/Lqmcwhw0/

Thanks.

**Comment by randyaskin** [comment]
Closing due to age. Please let us know if this is still an issue that you can replicate independently.
