### ISSUE TITLE
px-alert-message will hang in Windows Firefox

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-alert-message#14]
The following loop is running forever in Win Firefox and cause firefox to show the stop long running script popup.

// the following code is always true in Window Firefox
while(messageDiv.scrollHeight > messageDiv.offsetHeight)  {
....
}

I think adding a threshold will stop the compare 
while((messageDiv.scrollHeight - messageDiv.offsetHeight) >=** this._threshold**) {
.....
}

**Comment by mdwragg** [comment]
Hi @Menkhaus-ge - if you could take a look at this issue @clementchi would be very grateful!

**Comment by Menkhaus-ge** [comment]
The issue ended up be with the line height. We adjusted the sass to fix this bug. 
Fixed in release 0.5.1
