### ISSUE TITLE
In px-alert-message , message-title and  message attributes not working .

### ISSUE THREAD

**Issue by avdheshchouhan** [PredixDev/px-alert-message#16]
<px-alert-message
    						type="important"
   							 message-title="Heads up!"
   							 message="This definitely needs our attention."
    							action="https://www.predix.io/"
  							  auto-dismiss="5000">
						</px-alert-message>

message-title and  message attributes not working .

**Comment by nonmetalhail** [comment]
Hi, your code appears to work fine in jsfiddle:

https://jsfiddle.net/nahman/bapq4891/

Are you importing the component correctly?

**Comment by avdheshchouhan** [comment]
Hi Elliot ,


Thanks for the reply .

I have imported the files correctly .


The output which I am getting is 



Not able to display :
 message-title="Heads up!" 
 message="This definitely needs our attention."

Thanks and Regards
Avdhesh Singh Chouhan

**Comment by nonmetalhail** [comment]
I'm sorry, but we cannot troubleshoot with such limited information. Please provide a jsfiddle, Gist, or the like demonstrating the issue.

**Comment by westergaards** [comment]
I know this is a little old, but just case someone else runs into the same issue. ..In our scenario we have bootstrap.min included in our app.. The 'collapse' class that is being added to the message div is being overridden with display:none from bootstrap.. Is it possible to rename the class to something else to avoid future collisions and troubleshooting time?

**Comment by randyaskin** [comment]
Updated in v0.6.6. Thanks @westergaards 

@avdheshchouhan - could this be the same reason you were having issues?

**Comment by avdheshchouhan** [comment]
Yes thanks for the reply . I was able to fix that few months back. But yes 
the issue was same ' bootstrap css over ride' .

Thanks & Regards
Avdhesh Singh Chouhan
Follow me on KNOME: https://knome.ultimatix.net/u/avdhesh.chouhan
Tata Consultancy Services
4th to 7th Floors,Building B2,Plot No.20 & 21,Sector - 135,
Seaview Developers Ltd.,SEZ
Noida - 201301,Uttar Pradesh
India
Ph:- +91 0120 6746019
Mailto: avdhesh.chouhan@tcs.com
Website: http://www.tcs.com
____________________________________________
Experience certainty.   IT Services
                        Business Solutions
                        Consulting
____________________________________________
