### ISSUE TITLE
Type="Custom" is replacing icon with additional px-alert-message

### ISSUE THREAD

**Issue by ashleydf** [PredixDev/px-alert-message#17]
This is inside an Angular App. Not able to use type="custom" and input unique icons/images. 
## Expected behavior and actual behavior:

Expected: ability to provide custom icons on left-hand side of message
Actual: Repeated px-alert-message on top trying to fit in the icon div
## Steps to reproduce the problem:

Copied custom type demo html from GitHub 
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

component version: "px-alert-message": "^0.5.4",
Browser: Chrome Version 52.0.2743.116 (64-bit)
Mac Os
## Screenshots (_optional, but very helpful_):

![screen shot 2016-08-18 at 12 45 13 pm](https://cloud.githubusercontent.com/assets/14944323/17788268/a81e94ca-6541-11e6-874c-7710d051838d.png)
## Code examples help us better understand the issue - follow the [CodePen](http://codepen.io/mdwragg/pen/LNwmpB) or [jsfiddle](https://jsfiddle.net/Lqmcwhw0/3/), templates, which both use polygit, to help explain the issue.

<px-alert-message
    type="custom"
    message-title="Custom Alert"
    message="The icon to the left is defined by placing content between the px-alert-message tags. If applicable it is possible to have various file types."
    action="https://www.predix.io/">
    <img src="http://img2.wikia.nocookie.net/__cb20101017002729/logopedia/images/1/19/500px-General_Electric_logo_svg.png"/>
  </px-alert-message>

**Comment by randyaskin** [comment]
It looks like this is a known issue with using Angular and Polymer together, since both use the `<content>` tag for transclusion.

See [here](https://github.com/angular/angular.js/issues/12410) and [here](http://stackoverflow.com/questions/34779175/polymer-elements-within-angular-2-component) for more information.

**Comment by randyaskin** [comment]
@ashleydf is this issue still outstanding or can it be closed?
