### ISSUE TITLE
Change message title conflicts with "Show More / Show Less"

### ISSUE THREAD

**Issue by appagg** [PredixDev/px-alert-message#19]
1. From the demo where the message is long and has the 'Show More' link
2. click the link to show more
2. Change the message title from the input
3. click the 'show less' then 'show more' again, the title reverts back to its original value

![screen shot 2016-12-02 at 11 33 42 am](https://cloud.githubusercontent.com/assets/1781887/20847495/356d6d08-b883-11e6-947d-9be383889df3.png)

**Comment by randyaskin** [comment]
@appagg I tweaked your message a little. The words "Show More" are not getting appended, they're already present in that "message title" input box (you may have to scroll right to see them). But you are correct that the show less / show more links are causing it to revert back to the original value for message-title. We'll have to look into whether this is an actual bug, or just a weird artifact of the way the demo page does binding between the inputs and the alert-message demo.

**Comment by randyaskin** [comment]
Fixed in v0.9.2.
