### ISSUE TITLE
Message truncation is not dynamic

### ISSUE THREAD

**Issue by Menkhaus-ge** [PredixDev/px-alert-message#25]
The expected behavior is that the button 'show more' would only show on alert messages that have text longer than 3 lines. 

1. Open new-demo branch and run the demo. 
2. select 'long message' tab
3. select other tab and the 'show more' button does not disappear 

Branch new-demo

Expected:
![screen shot 2017-02-08 at 10 21 10 am](https://cloud.githubusercontent.com/assets/14931112/22751259/9eb63b60-ede8-11e6-842a-1cd352116053.png)

Bug:
![screen shot 2017-02-08 at 10 21 01 am](https://cloud.githubusercontent.com/assets/14931112/22751271/a9cd40ca-ede8-11e6-9778-0dff283c6ba4.png)

possible problem: 
We suspect that there are life-cycle issues with when _checkMessageLength function is being called/implemented. https://github.com/PredixDev/px-alert-message/blob/master/px-alert-message.html#L352

**Comment by randyaskin** [comment]
Fixed in v0.9.2.
