### ISSUE TITLE
General Question- Why polymer font awesome and not px-iconography-design ?

### ISSUE THREAD

**Issue by sumeet-singh04** [PredixDev/px-alert-message#26]
Why is px-alert-message using polymer-font-awesome instead of using Predix defined px-iconography-design library?

**Comment by randyaskin** [comment]
Px-iconography-design is a sass partial that uses the FontAwesome icon font, whereas px-polymer-font-awesome is a Polymer component that leverages iron-icon and an SVG version of each of the FontAwesome icons. The current trend in web development is to move from icon fonts to SVG for various reasons (accessibility, multi-color icons, crisper rendering at small sizes, etc). There are a number of great articles on the topic which you should be able to find easily via Google.
