### ISSUE TITLE
No 'OK' text when I have the acknowledge action specified

### ISSUE THREAD

**Issue by benmak11** [PredixDev/px-alert-message#29]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
![screen shot 2017-03-21 at 2 16 47 pm](https://cloud.githubusercontent.com/assets/6559240/24163478/1d039b3e-0e41-11e7-84ed-c2d42deaa215.png)
## Steps to reproduce the problem:

Step 1: component fixture is as follows:

`<div class="alert-message-div">
      <template is="dom-if" if="{{noDropdownSelectionMsg}}">
                        <px-alert-message id="error-noDropDown-Select"
                                          type="important"
                                          message-title="[[errors.noDropdownTitle]]"
                                          message="[[errors.noDropdownMessage]]"
                                          action="acknowledge"
                                          language="en">
                        </px-alert-message>
                      </template>
                    </div>`

but I get this

<img width="403" alt="screen shot 2017-03-21 at 2 17 06 pm" src="https://cloud.githubusercontent.com/assets/6559240/24163515/3259fed8-0e41-11e7-8ade-e503e2317f48.png">

I wanted to find out if this can be addressed so I can get the 'OK' text back.

Thanks

**Comment by randyaskin** [comment]
It's working on our demo page for `action=acknowledge`... is this in your local, have you run `bower install` or `bower update` lately? We added a dependency for `app-localize-behavior`, do you see any error messages in your console about it missing?

**Comment by benmak11** [comment]
Hi @randyaskin,

Yes this is on a local run and yes I did perform a `bower update` but I still get this issue. The only error messages I see in my console are for fontawesome but that's unrelated to the `app-localize-behavior` dependency.

<img width="723" alt="screen shot 2017-03-22 at 5 32 55 pm" src="https://cloud.githubusercontent.com/assets/6559240/24221697/cc8a53c4-0f25-11e7-92e0-66e74ebc10c3.png">

The funny thing is the "OK" texts starts to show if I navigate away from that page, perform a CRUD method (GET, POST or UPDATE call from the service), navigate back to the initial page and do the same error action

**Comment by randyaskin** [comment]
When you pasted your fixture code it said `language="en"` but your console log says localized with `en-us` - could it be that? We didn't include `en-us` in our locales.json

@mdwragg we default language to `en` but I wonder if we should also set `useKeyIfMissing="true"` on all of our localizations, so if they pass an invalid or unsupported language property, we have a fallback.

**Comment by randyaskin** [comment]
Actually, re-reading your last bit makes it sound more like a race condition on loading of the locales.json or calling the localize method or something. Any insights from your testing, @mdwragg ?

**Comment by benmak11** [comment]
@randyaskin so we have our own localization managed by [spog-components](https://github.com/bms-spog/spog-components). This is the i18n portion that allocates our localization. So that might be causing the race condition... It might help you dig into the problem @mdwragg

**Comment by mdwragg** [comment]
@benmak11 - can you create me a minimal repo to allow me to recreate this? Thanks.

**Comment by benmak11** [comment]
Just use [this repo](https://github.build.ge.com/BM/wip-uApp) with the [ui-app-hub](https://github.build.ge.com/hubs/ui-app-hub). You need ui-app-hub to be running first to populate the app.

**Comment by mdwragg** [comment]
I don't know how to set all that up @benmak11. Can you show us this issue outside all of that please?

**Comment by benmak11** [comment]
Hi @mdwragg I could not recreate this issue on a standard app while running it with node. I think it might go back to @randyaskin's suggestion that we have a i18n localization using 'en-us' instead of 'en'. The "OK" text is not shown at first but after navigating away from page and then going back then its populated...
