### ISSUE TITLE
Have string element within the warning icon

### ISSUE THREAD

**Issue by adeetshah** [PredixDev/px-alert-message#3]
Is it possible to have any string element (example: '!' ) within the diamond warning icon ?

<img width="130" alt="screen shot 2015-10-21 at 4 36 18 pm" src="https://cloud.githubusercontent.com/assets/14948186/10653192/0f04c9fc-7812-11e5-8338-57239fa574c6.png">

**Comment by Menkhaus-ge** [comment]
You cannot replace the numbers in the alert icons. You can use type="custom" to add a custom icon. There is an example of this in the demo page. http://predixdev.github.io/px-alert-message/px-alert-message/
