### ISSUE TITLE
Regression in localization behavior change causes component to fail

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-alert-message#33]
Looks like 076be13e22ce8efbd2149f7022bf5c75d20ccf1d may have introduced a regression in the localization behavior that causes the component to fail to load in some browsers. ([Failing tests here.](https://travis-ci.org/PredixDev/px-alert-message/jobs/233444567))

@benoitjchevalier or @randyaskin - could either of you take a look when you have a chance? Think you two have been deep into the localization switch, right? Thanks.

**Expected behavior and actual behavior:**

Component should load correctly in Safari. Right now it fails to load because of a thrown TypeError coming from the `_computeLocalize` method.

**Steps to reproduce the problem:**

Open the [px-alert-message demo page](https://www.predix-ui.com/px-alert-message/px-alert-message/) in Safari 9 or Safari 10. The page will fail to load correctly and an error will be logged to the console:

![image](https://cloud.githubusercontent.com/assets/6456757/26512165/30effaa4-421a-11e7-9a7e-a782dfa79a90.png)

**Environment:**

* Mac OS X 10.11.6
* Safari 9.1.2
* px-alert-message v0.9.6

**Comment by benoitjchevalier** [comment]
Have you tried blasting the bower components? I think the safari 9 issue has been fixed in app-localize-behavior > 1.0.0: https://github.com/PolymerElements/app-localize-behavior/issues/92
The tests were genuinely failing for changing the "show more/show less" button so I've fixed that as well.
