### ISSUE TITLE
Uncaught ReferenceError: IntlMessageFormat is not defined

### ISSUE THREAD

**Issue by sachinkantipudi** [PredixDev/px-alert-message#38]
With the latest version, I'm getting this reference error in the browser, and it's not showing up.

**Comment by randyaskin** [comment]
I have not seen this error. It looks like intl-messageformat is a bower dependency of this component (probably coming from app-localize-behavior which we use for l10n). Are you able to reproduce this in a CodePen or JSFiddle?

**Comment by sachinkantipudi** [comment]
I do not see it in CodePen, just in my project. Just couldn't figure out why, may be because of webpack module bundling.

**Comment by sachinkantipudi** [comment]
It's because of webpack's module bundling, which is creating a closure on intlMessageFormat and making it unavailable in window level.

**Comment by pkshah2017** [comment]
Hey I'm running into this same issue. I am using webpack to bundle as well. How did you fix this issue?
