### ISSUE TITLE
The alert message fires px-alert-message-hidden when auto-dismiss is set to some number(only  on first show)

### ISSUE THREAD

**Issue by Shibham** [PredixDev/px-alert-message#39]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by Shibham** [comment]
<px-alert-message
        type="information"
        auto-dismiss="5000"
        action="https://www.google.com/chrome/browser/desktop/index.html"
        message-title="Unsupported Browser Version!"
        message="{{errorMessageTag}}"
        hide-severity
        hide-badge>
      </px-alert-message>

**Comment by randyaskin** [comment]
Please fill out the template when opening an issue, it's there for a reason. From your description it sounds like it's doing exactly what it's supposed to - firing an event when the message is hidden.
