### ISSUE TITLE
visible property not working as expected

### ISSUE THREAD

**Issue by shrikumarhegde** [PredixDev/px-alert-message#40]
Hi There,

visible: boolean = false property is not working as expected. 

visible=true or visible=false both are showing the alert box. only removing visible property to hide the alert box on load. 

Is there anyway to make visible =false so that we can update true/false dynamically when needed ?

**Comment by randyaskin** [comment]
According to the HTML spec, this is how boolean attributes are _expected_ to function:
https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes

You can set it dynamically using vanilla JavaScript (`myMessage.visible = false`), or whatever framework you prefer should provide a way of binding to booleans.
