### ISSUE TITLE
Message is truncated in chrome and firefox

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-alert-message#8]
Message is truncated in firefox if the message-title and message are long. Chrome is fine. 

e.g. 

            <px-alert-message
                type="error"
                message-title="A configuration package must be deployed to the device before you can deploy software packages."
                message="Schedule configuration package deployments earlier than software package deployments.">
            </px-alert-message>

![screen shot 2016-01-28 at 12 33 13 pm](https://cloud.githubusercontent.com/assets/997551/12658082/bf913ab6-c5bb-11e5-9dff-ade5c7f6e60b.png)

**Comment by mdwragg** [comment]
@Menkhaus-ge - will this be addressed by the fix you're working on?

**Comment by Menkhaus-ge** [comment]
In v0.3.0 the message now truncates after three lines and adds an action allowing the user to expand full message.
